version: "3.9"
services:
  backend:
    build: ./backend
    environment:
      ROCKET_ENV: debug
      ROCKET_ADDRESS: 0.0.0.0
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "9000:80"
