name: CI
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install modules
              run: cd frontend && npm i
            - name: Run ESLint
              run: eslint

    lint:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run ESLint
              run: eslint

    type-check:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run ESLint
              run: tsc --noEmit
